version: "3"
services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=todo
  backend:
    image: apletenev/todo:1
    ports:
      - "8443:8443"
    depends_on:
      - db