spring:
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo?characterEncoding=utf8
    username: postgres
    password: Vfj6di
  flyway:
    url: jdbc:postgresql://localhost:5432/todo?characterEncoding=utf8
    user: postgres
    password: Vfj6di
    enabled: true
    locations: "classpath:db/migration"
server:
  ssl:
    key-store: src/main/resources/springboot.p12
    key-store-password: 9cgYQ4
    key-store-type: pkcs12
    key-alias: testkey
    key-password: 9cgYQ4
  port: 8443

---
spring:
  config:
    activate:
      on-profile: security_test

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:mydb
    user: sa
    password: password
    enabled: true
    locations: "classpath:db/migration"
server:
  ssl:
    key-store: src/main/resources/springboot.p12
    key-store-password: 9cgYQ4
    key-store-type: pkcs12
    key-alias: testkey
    key-password: 9cgYQ4
  port: 8443
---
spring:
  config:
    activate:
      on-profile: nosecurity_test

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:mydb
    user: sa
    password: password
    enabled: true
    locations: "classpath:db/migration"