spring:
  profiles:
    active: dev
    group:
      dev:
        - "h2"
      prod:
        - "secure"
        - "pg_docker_compose"
      security_test:
        - "secure"
        - "pg_local"
      nosecurity_test:
        - "pg_local"

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
---
spring:
  config:
    activate:
      on-profile: secure
server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: 9cgYQ4
    key-store-type: pkcs12
    key-alias: testkey
    key-password: 9cgYQ4
  port: 8443

---
spring:
  config:
    activate:
      on-profile: pg_local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo?characterEncoding=utf8
    username: postgres
    password: postgrespw
  flyway:
    url: jdbc:postgresql://localhost:5432/todo?characterEncoding=utf8
    user: postgres
    password: postgrespw
    enabled: true
    locations: "classpath:db/migration"

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

---
spring:
  config:
    activate:
      on-profile: pg_docker_compose

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/todo?characterEncoding=utf8
    username: postgres
    password: postgrespw
  flyway:
    url: jdbc:postgresql://db:5432/todo?characterEncoding=utf8
    user: postgres
    password: postgrespw
    enabled: true
    locations: "classpath:db/migration"


---
spring:
  config:
    activate:
      on-profile: h2

  datasource:
#    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    url: jdbc:h2:file:./mydb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
#    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    url: jdbc:h2:file:./mydb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    user: sa
    password: password
    enabled: true
    locations: "classpath:db/migration"
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

