spring:
  profiles:
    active: test
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo?characterEncoding=utf8
    username: postgres
    password: Vfj6di
  flyway:
    url: jdbc:postgresql://localhost:5432/todo?characterEncoding=utf8
    user: postgres
    password: Vfj6di
    enabled: true
    locations: "classpath:db/migration"

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:mydb
    user: sa
    password: password
    enabled: true
    locations: "classpath:db/migration"
---
spring:
  config:
    activate:
      on-profile: nosecurity_test

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:mydb
    user: sa
    password: password
    enabled: true
    locations: "classpath:db/migration"